# Generated by Django 5.0.3 on 2024-03-22 20:14

import rhombus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhombus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='data_type',
            field=models.CharField(max_length=50, validators=[rhombus.models.validate_data_type]),
        ),
    ]
