# Generated by Django 5.0.3 on 2024-03-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhombus', '0002_alter_column_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='data_type',
            field=models.CharField(max_length=50),
        ),
    ]
